import type { NewAccessorial } from '../db/schema.js';

/**
 * Expanded add-on library for Phase B.
 *
 * These are seeded as tenant-owned rows so every carrier can enable/disable,
 * rename, and re-price them. Amounts are only starting defaults — carriers
 * should tune them to their own terminals, equipment, and customer tariffs.
 */
export const EXPANDED_ACCESSORIAL_LIBRARY: Omit<NewAccessorial, 'tenantId'>[] = [
  // ── Drayage / container-specific ──────────────────────────────────
  {
    code: 'chassis_rental',
    label: 'Chassis Rental',
    description: 'Daily chassis rental charged when chassis is needed for the move.',
    kind: 'per_day',
    amount: 40,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 101,
  },
  {
    code: 'chassis_reposition',
    label: 'Chassis Repositioning',
    description: 'Repositioning chassis before pickup or after empty return.',
    kind: 'flat',
    amount: 175,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 102,
  },
  {
    code: 'chassis_flip',
    label: 'Chassis Flip',
    description: 'Flip or lift required to transfer container/chassis setup.',
    kind: 'flat',
    amount: 150,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 103,
  },
  {
    code: 'empty_return_split',
    label: 'Empty Return Split',
    description: 'Empty container must be returned to a different location than normal.',
    kind: 'flat',
    amount: 125,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 104,
  },
  {
    code: 'yard_pull',
    label: 'Yard Pull',
    description: 'Pull container or trailer from carrier yard for customer move.',
    kind: 'flat',
    amount: 125,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 105,
  },
  {
    code: 'terminal_wait_time',
    label: 'Terminal Wait Time',
    description: 'Driver wait time at marine terminal or rail ramp after free time.',
    kind: 'per_hour',
    amount: 95,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 106,
  },
  {
    code: 'appointment_fee',
    label: 'Terminal Appointment Fee',
    description: 'Admin/operational fee for terminal or warehouse appointment handling.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 107,
  },
  {
    code: 'scale_ticket',
    label: 'Scale Ticket',
    description: 'Certified scale ticket or weight check.',
    kind: 'flat',
    amount: 35,
    trigger: 'optional',
    appliesToServices: ['drayage', 'ftl', 'hotshot'],
    enabled: true,
    sortOrder: 108,
  },
  {
    code: 'tri_axle',
    label: 'Tri-axle Chassis',
    description: 'Tri-axle chassis required for heavy container moves.',
    kind: 'flat',
    amount: 250,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 109,
  },
  {
    code: 'bonded_move',
    label: 'Bonded / In-bond Move',
    description: 'Bonded move, in-bond handling, or customs-controlled delivery support.',
    kind: 'flat',
    amount: 150,
    trigger: 'optional',
    appliesToServices: ['drayage', 'ftl'],
    enabled: true,
    sortOrder: 111,
  },
  {
    code: 'terminal_fee',
    label: 'Terminal Fee',
    description: 'Terminal-specific fee or admin pass-through configured by the carrier.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 112,
  },
  {
    code: 'port_congestion',
    label: 'Port Congestion Surcharge',
    description: 'Surcharge for unusually slow terminal conditions or congestion.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 113,
  },
  {
    code: 'weekend_after_hours',
    label: 'Weekend / After-hours',
    description: 'Pickup or delivery outside normal business hours.',
    kind: 'flat',
    amount: 175,
    trigger: 'optional',
    appliesToServices: ['drayage', 'ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 114,
  },
  {
    code: 'reefer_monitoring',
    label: 'Reefer Monitoring',
    description: 'Temperature monitoring/checks while reefer container is in custody.',
    kind: 'per_day',
    amount: 35,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 115,
  },
  {
    code: 'genset_fuel',
    label: 'Genset Fuel / Runtime',
    description: 'Fuel/runtime allowance for genset-powered reefer container moves.',
    kind: 'per_day',
    amount: 85,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 116,
  },
  {
    code: 'demurrage_admin',
    label: 'Demurrage Admin',
    description: 'Admin handling for demurrage coordination or pass-through processing.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: false,
    sortOrder: 117,
  },
  {
    code: 'per_diem_admin',
    label: 'Per Diem Admin',
    description: 'Admin handling for per diem coordination or pass-through processing.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: false,
    sortOrder: 118,
  },
  {
    code: 'clean_truck_fee',
    label: 'Clean Truck / Port Fee',
    description: 'Port-specific truck compliance or clean-truck program fee.',
    kind: 'flat',
    amount: 35,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: false,
    sortOrder: 119,
  },

  // ── Universal trucking extras ─────────────────────────────────────
  {
    code: 'toll_pass_through',
    label: 'Tolls',
    description: 'Tolls, bridges, tunnels, or road charges.',
    kind: 'flat',
    amount: 0,
    trigger: 'optional',
    appliesToServices: ['drayage', 'ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: false,
    sortOrder: 410,
  },
  {
    code: 'redelivery',
    label: 'Redelivery',
    description: 'Second delivery attempt after customer/receiver is unavailable.',
    kind: 'flat',
    amount: 175,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot', 'drayage'],
    enabled: true,
    sortOrder: 420,
  },
  {
    code: 'limited_access',
    label: 'Limited Access',
    description: 'Pickup or delivery at limited-access location.',
    kind: 'flat',
    amount: 95,
    trigger: 'optional',
    appliesToServices: ['ltl', 'expedited', 'ftl'],
    enabled: true,
    sortOrder: 430,
  },
  {
    code: 'sort_and_segregate',
    label: 'Sort & Segregate',
    description: 'Driver/carrier must sort, count, or segregate freight.',
    kind: 'flat',
    amount: 125,
    trigger: 'optional',
    appliesToServices: ['ltl', 'expedited', 'ftl'],
    enabled: true,
    sortOrder: 440,
  },
  {
    code: 'lumper',
    label: 'Lumper / Unloading Fee',
    description: 'Warehouse lumper or unloading fee.',
    kind: 'flat',
    amount: 150,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited'],
    enabled: true,
    sortOrder: 450,
  },
  {
    code: 'driver_wait_pickup',
    label: 'Pickup Waiting Time',
    description: 'Driver wait time at pickup after free time.',
    kind: 'per_hour',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 460,
  },
  {
    code: 'driver_wait_delivery',
    label: 'Delivery Waiting Time',
    description: 'Driver wait time at delivery after free time.',
    kind: 'per_hour',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 470,
  },

  // ── Open deck / special equipment ─────────────────────────────────
  {
    code: 'extra_straps_chains',
    label: 'Extra Straps / Chains',
    description: 'Additional securement equipment required beyond standard setup.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'hotshot'],
    enabled: true,
    sortOrder: 510,
  },
  {
    code: 'oversize_permit',
    label: 'Oversize Permit',
    description: 'Permit required because cargo exceeds standard legal dimensions.',
    kind: 'flat',
    amount: 250,
    trigger: 'optional',
    appliesToServices: ['ftl', 'hotshot'],
    enabled: true,
    sortOrder: 520,
  },
  {
    code: 'pilot_car',
    label: 'Pilot Car / Escort',
    description: 'Pilot car or escort requirement for oversized move.',
    kind: 'flat',
    amount: 650,
    trigger: 'optional',
    appliesToServices: ['ftl', 'hotshot'],
    enabled: false,
    sortOrder: 530,
  },
];
