import type { NewAccessorial } from '../db/schema.js';

/**
 * Expanded add-on library for Phase B.
 *
 * These are seeded as tenant-owned rows so every carrier can enable/disable,
 * rename, and re-price them. Amounts are only starting defaults — carriers
 * should tune them to their own terminals, equipment, and customer tariffs.
 *
 * NOTE: the core real-drayage schedule (chassis rental/split/positioning,
 * flip, triaxle, pre-pull, wait time, hazardous, in-bond, reefer, tolls,
 * yard/reefer storage, weekend, rail-terminal, detention) now lives in
 * DEFAULT_ACCESSORIALS (defaults.ts) so it seeds to every tenant + the
 * drayage onboarding template. Codes must stay UNIQUE across both files —
 * the accessorials:seed script merges them and dedupes by `code`.
 */
export const EXPANDED_ACCESSORIAL_LIBRARY: Omit<NewAccessorial, 'tenantId'>[] = [
  // ── Drayage / container-specific ──────────────────────────────────
  {
    code: 'chassis_reposition',
    label: 'Chassis Repositioning',
    description: 'Repositioning chassis before pickup or after empty return.',
    kind: 'flat',
    amount: 175,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 102,
  },
  {
    code: 'empty_return_split',
    label: 'Empty Return Split',
    description: 'Empty container must be returned to a different location than normal.',
    kind: 'flat',
    amount: 125,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 104,
  },
  {
    code: 'yard_pull',
    label: 'Yard Pull',
    description: 'Pull container or trailer from carrier yard for customer move.',
    kind: 'flat',
    amount: 125,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 105,
  },
  {
    code: 'terminal_wait_time',
    label: 'Terminal Wait Time',
    description: 'Driver wait time at marine terminal or rail ramp after free time.',
    kind: 'per_hour',
    amount: 95,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 106,
  },
  {
    code: 'appointment_fee',
    label: 'Terminal Appointment Fee',
    description: 'Admin/operational fee for terminal or warehouse appointment handling.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 107,
  },
  {
    code: 'scale_ticket',
    label: 'Scale Ticket',
    description: 'Certified scale ticket or weight check.',
    kind: 'flat',
    amount: 35,
    trigger: 'optional',
    appliesToServices: ['drayage', 'ftl', 'hotshot'],
    enabled: true,
    sortOrder: 108,
  },
  {
    code: 'terminal_fee',
    label: 'Terminal Fee',
    description: 'Terminal-specific fee or admin pass-through configured by the carrier.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 112,
  },
  {
    code: 'port_congestion',
    label: 'Port Congestion Surcharge',
    description: 'Surcharge for unusually slow terminal conditions or congestion.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 113,
  },
  {
    code: 'weekend_after_hours',
    label: 'Weekend / After-hours',
    description: 'Pickup or delivery outside normal business hours.',
    kind: 'flat',
    amount: 175,
    trigger: 'optional',
    appliesToServices: ['drayage', 'ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 114,
  },
  {
    code: 'reefer_monitoring',
    label: 'Reefer Monitoring',
    description: 'Temperature monitoring/checks while the reefer is in custody (container yard or over-the-road).',
    kind: 'per_day',
    amount: 35,
    trigger: 'optional',
    // Broadened to over-the-road reefer FTL as well — the reefer onboarding
    // template offers temp-monitoring as an editable default add-on.
    appliesToServices: ['drayage', 'ftl'],
    enabled: true,
    sortOrder: 115,
  },
  {
    code: 'genset_fuel',
    label: 'Genset Fuel / Runtime',
    description: 'Fuel/runtime allowance for genset-powered reefer container moves.',
    kind: 'per_day',
    amount: 85,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: true,
    sortOrder: 116,
  },
  {
    code: 'demurrage_admin',
    label: 'Demurrage Admin',
    description: 'Admin handling for demurrage coordination or pass-through processing.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: false,
    sortOrder: 117,
  },
  {
    code: 'per_diem_admin',
    label: 'Per Diem Admin',
    description: 'Admin handling for per diem coordination or pass-through processing.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: false,
    sortOrder: 118,
  },
  {
    code: 'clean_truck_fee',
    label: 'Clean Truck / Port Fee',
    description: 'Port-specific truck compliance or clean-truck program fee.',
    kind: 'flat',
    amount: 35,
    trigger: 'optional',
    appliesToServices: ['drayage'],
    enabled: false,
    sortOrder: 119,
  },

  // ── Universal trucking extras ─────────────────────────────────────
  {
    code: 'redelivery',
    label: 'Redelivery',
    description: 'Second delivery attempt after customer/receiver is unavailable.',
    kind: 'flat',
    amount: 175,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot', 'drayage'],
    enabled: true,
    sortOrder: 420,
  },
  {
    code: 'limited_access',
    label: 'Limited Access',
    description: 'Pickup or delivery at limited-access location.',
    kind: 'flat',
    amount: 95,
    trigger: 'optional',
    appliesToServices: ['ltl', 'expedited', 'ftl'],
    enabled: true,
    sortOrder: 430,
  },
  {
    code: 'sort_and_segregate',
    label: 'Sort & Segregate',
    description: 'Driver/carrier must sort, count, or segregate freight.',
    kind: 'flat',
    amount: 125,
    trigger: 'optional',
    appliesToServices: ['ltl', 'expedited', 'ftl'],
    enabled: true,
    sortOrder: 440,
  },
  {
    code: 'lumper',
    label: 'Lumper / Unloading Fee',
    description: 'Warehouse lumper or unloading fee.',
    kind: 'flat',
    amount: 150,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited'],
    enabled: true,
    sortOrder: 450,
  },
  {
    code: 'driver_wait_pickup',
    label: 'Pickup Waiting Time',
    description: 'Driver wait time at pickup after free time.',
    kind: 'per_hour',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 460,
  },
  {
    code: 'driver_wait_delivery',
    label: 'Delivery Waiting Time',
    description: 'Driver wait time at delivery after free time.',
    kind: 'per_hour',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 470,
  },

  // ── Open deck / special equipment ─────────────────────────────────
  {
    code: 'extra_straps_chains',
    label: 'Extra Straps / Chains',
    description: 'Additional securement equipment required beyond standard setup.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'hotshot'],
    enabled: true,
    sortOrder: 510,
  },
  {
    code: 'oversize_permit',
    label: 'Oversize Permit',
    description: 'Permit required because cargo exceeds standard legal dimensions.',
    kind: 'flat',
    amount: 250,
    trigger: 'optional',
    appliesToServices: ['ftl', 'hotshot'],
    enabled: true,
    sortOrder: 520,
  },
  {
    code: 'pilot_car',
    label: 'Pilot Car / Escort',
    description: 'Pilot car or escort requirement for oversized move.',
    kind: 'flat',
    amount: 650,
    trigger: 'optional',
    appliesToServices: ['ftl', 'hotshot'],
    enabled: false,
    sortOrder: 530,
  },

  // ── Delivery / location-type services ─────────────────────────────
  // Trucking/drayage-relevant "additional services" (from Alex's carrier
  // service menu). Air/ocean-forwarding-only services (airline, Amazon FBA,
  // ocean CFS, TSA, alcohol-license) are intentionally excluded. The prices
  // below are EDITABLE STARTING DEFAULTS — carriers set their real numbers
  // per location/customer (many are "quote on request"). The schema has no
  // pickup-vs-delivery scope yet, so these are flat location surcharges;
  // per-leg (pickup vs delivery) scoping is a future enhancement.
  {
    code: 'construction_site',
    label: 'Construction Site',
    description: 'Delivery/pickup at an active construction site. Editable default.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot', 'drayage'],
    enabled: true,
    sortOrder: 610,
  },
  {
    code: 'delivery_notification',
    label: 'Delivery Notification',
    description: 'Call-ahead / appointment notification before delivery. Editable default.',
    kind: 'flat',
    amount: 15,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot', 'drayage'],
    enabled: true,
    sortOrder: 620,
  },
  {
    code: 'military_base',
    label: 'Military Base',
    description: 'Delivery/pickup at a military base (gate/escort handling). Editable default.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot', 'drayage'],
    enabled: true,
    sortOrder: 630,
  },
  {
    code: 'school',
    label: 'School',
    description: 'Delivery/pickup at a school or university. Editable default.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 640,
  },
  {
    code: 'trade_show',
    label: 'Trade Show',
    description: 'Delivery/pickup at a convention or trade-show venue. Editable default.',
    kind: 'flat',
    amount: 150,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 650,
  },
  {
    code: 'hotel',
    label: 'Hotel',
    description: 'Delivery/pickup at a hotel or resort. Editable default.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'hotshot'],
    enabled: true,
    sortOrder: 660,
  },
  {
    code: 'protect_from_freeze',
    label: 'Protect from Freeze',
    description: 'Freight must be kept above freezing in transit. Editable default.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited', 'drayage'],
    enabled: true,
    sortOrder: 670,
  },
  {
    code: 'fragile_handling',
    label: 'Fragile — Limited Handling',
    description: 'Fragile freight requiring careful / limited handling. Editable default.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['ftl', 'ltl', 'expedited'],
    enabled: true,
    sortOrder: 680,
  },

  // ── Vertical-default add-ons (dry-van / reefer / flatbed / hotshot / LTL) ──
  // Standard per-vertical accessorials that the onboarding seed templates
  // default-select but which the shared catalog above didn't yet carry. Every
  // amount is an EDITABLE, industry-default STARTING POINT — carriers re-price
  // these per lane / customer in the dashboard or AI chat, same convention as
  // the drayage schedule in defaults.ts.
  {
    code: 'reefer_precool',
    label: 'Reefer Pre-Cool',
    description: 'Pre-cool the trailer to the set temperature before loading. Editable default.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['ftl', 'drayage'],
    enabled: true,
    sortOrder: 320,
  },
  {
    code: 'reefer_washout',
    label: 'Reefer Washout',
    description: 'Trailer washout between temperature-controlled loads (food-grade / allergen). Editable default.',
    kind: 'flat',
    amount: 50,
    trigger: 'optional',
    appliesToServices: ['ftl', 'drayage'],
    enabled: true,
    sortOrder: 322,
  },
  {
    code: 'coil_rack',
    label: 'Coil Rack / Special Securement',
    description: 'Coil rack or specialized securement for steel coils and similar loads. Editable default.',
    kind: 'flat',
    amount: 75,
    trigger: 'optional',
    appliesToServices: ['ftl'],
    enabled: true,
    sortOrder: 540,
  },
  {
    code: 'expedite_fee',
    label: 'Expedite / Rush Fee',
    description: 'Premium for guaranteed / same-day / team-driver expedited service. Editable default.',
    kind: 'flat',
    amount: 150,
    trigger: 'optional',
    appliesToServices: ['hotshot', 'expedited'],
    enabled: true,
    sortOrder: 480,
  },
  {
    code: 'reweigh_reclass',
    label: 'Reweigh / Reclass',
    description: 'Carrier re-weighs or re-classes the shipment when the declared weight/class is wrong. Editable default.',
    kind: 'flat',
    amount: 45,
    trigger: 'optional',
    appliesToServices: ['ltl'],
    enabled: true,
    sortOrder: 245,
  },
  {
    code: 'overlength',
    label: 'Overlength Freight',
    description: 'Handling surcharge for freight over standard length (typically 8 ft+). Editable default.',
    kind: 'flat',
    amount: 95,
    trigger: 'optional',
    appliesToServices: ['ltl', 'ftl'],
    enabled: true,
    sortOrder: 248,
  },
];
