import { chromium } from '@playwright/test';
const BASE='http://localhost:8854'; const s=Date.now().toString(36);
const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:1440,height:300}});
await ctx.request.post(`${BASE}/api/auth/signup`,{data:{companyName:'Probe '+s,slug:'probe-'+s,email:`p+${s}@ex.com`,password:'GrabScroll123!',plan:'vital',countryFocus:'US',dpaAccepted:true,dpaVersion:'1.0'}});
const pg=await ctx.newPage(); await pg.goto(`${BASE}/app`,{waitUntil:'networkidle'}); await pg.waitForTimeout(1500);
await pg.evaluate(()=>{document.querySelectorAll('[class*="onboarding"]').forEach(n=>{if(n.style)n.style.display='none'})});
await pg.evaluate(()=>{const n=document.querySelector('.sidebar [data-route="rates"]'); if(n)n.click();}); await pg.waitForTimeout(1500);
const m=await pg.evaluate(()=>({innerH:innerHeight, docSH:document.scrollingElement.scrollHeight, bodySH:document.body.scrollHeight, shellH:(document.querySelector('.app-shell')||{}).scrollHeight, mainH:(document.querySelector('.app-main')||{}).scrollHeight, bodyOv:getComputedStyle(document.body).overflow, htmlOv:getComputedStyle(document.documentElement).overflow, shellOv:getComputedStyle(document.querySelector('.app-shell')).overflow}));
console.log(JSON.stringify(m,null,2));
await b.close();
