import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1100, height: 900 } });
page.on('console', m => console.log('[console]', m.type(), m.text()));
page.on('pageerror', e => console.log('[pageerror]', e.message));
page.on('requestfailed', r => console.log('[reqfail]', r.url(), r.failure()?.errorText));
await page.goto('http://localhost:8899/mock-host.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
const frames = page.frames().map(f => f.url());
console.log('FRAMES:', frames);
const frame = page.frames().find(f => f.url().includes('/w/demo'));
if (frame) {
  const bodyLen = await frame.evaluate(() => document.body ? document.body.innerHTML.length : -1);
  const hasCalc = await frame.evaluate(() => !!document.getElementById('qf-calc-btn'));
  const rootClass = await frame.evaluate(() => (document.getElementById('qf-root')||{}).className || 'NO ROOT');
  const err = await frame.evaluate(() => { const e=document.getElementById('qf-error'); return e? (e.style.display+' | '+e.textContent):'no err el'; });
  const bodyText = await frame.evaluate(() => (document.body.innerText||'').slice(0,300));
  console.log('bodyLen', bodyLen, 'hasCalc', hasCalc, 'rootClass', rootClass);
  console.log('errEl:', err);
  console.log('bodyText:', JSON.stringify(bodyText));
} else console.log('no widget frame found');
await browser.close();
