import { chromium } from '@playwright/test';
const b = await chromium.launch(); const p = await (await b.newContext({viewport:{width:1100,height:1000}})).newPage();
await p.goto('http://localhost:8854/w/demo?raw=1',{waitUntil:'networkidle'});
await p.waitForSelector('#qf-services button');
await p.click('#qf-services button[data-service="ftl"]'); await p.waitForTimeout(200);
await p.selectOption('#qf-equipment','dryvan').catch(()=>{});
await p.fill('#qf-pickup-zip','90001'); await p.fill('#qf-delivery-zip','90210'); await p.fill('#qf-weight','38000');
await p.click('#qf-calc-btn'); await p.waitForTimeout(2500);
const lines = await p.locator('#qf-step-quote .qf-result, .qf-result').innerText().catch(()=>'');
console.log('RESULT TEXT:\n'+lines.slice(0,600));
const bad = /% of linehaul|mi ×|was below minimum/.test(lines);
console.log('CONTAINS_MISLEADING_DESCRIPTOR:', bad);
await p.screenshot({path:'scratchpad/flagfix-1-honest-lines.png', fullPage:true});
await b.close();
process.exit(bad?1:0);
